name: Test Workflow Two
on:
  push:
    branches: [main]

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::123456789012:role/AnotherRole
