name: Test Workflow Two
on:
  push:
    branches: [main]

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::123456789012:role/AnotherRole
