name: Test Workflow Two
on:
  push:
    branches: [main]

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::123456789012:role/AnotherRole
